name: Manual redeployment workflow

on:
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3



      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq


      - name: Extract values from JSON
        run: |
          echo "vmType=$(jq -r '.vmType' config.json)" >> $GITHUB_ENV
          echo "contractAddress=$(jq -r '.contractAddress' config.json)" >> $GITHUB_ENV



      - name: Run additional commands
        run: |
          echo 'entered redepeloy step' 
          BASE_URL="https://a2d299f079aea4b82f155b0436fb8486.serveo.net/redeploy"
          PARAMS="?vmType=$vmType&repoUrl=https://github.com/$GITHUB_REPOSITORY.git&lastCommitHash=$GITHUB_SHA&redeployment=true"

          echo 'right before curl'
          RESPONSE=$(curl -s -o response.json -w "%{http_code}" "${BASE_URL}${PARAMS}")
          echo 'right after curl'

          if [[ ${RESPONSE} -ge 400 ]]; then
            echo "HTTP error occurred: ${RESPONSE}"
            cat response.json
            exit 1  # Exit with a non-zero status to fail the CI/CD pipeline
          fi

          echo "Success: ${RESPONSE}"
